version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi-logs:/app/logs  
    networks:
      - monitor-net

  loki:
    image: grafana/loki:2.9.3
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitor-net

  promtail:
    image: grafana/promtail:2.9.3
    volumes:
      - ./fastapi-logs:/var/log/fastapi  
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana-oss:10.4.1
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitor-net

volumes:
  grafana-storage:

networks:
  monitor-net:
