services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi-logs:/app/logs  
    networks:
      - monitor-net

  loki:
    image: grafana/loki:2.9.3
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitor-net

  promtail:
    image: grafana/promtail:2.9.3
    volumes:
      - ./fastapi-logs:/var/log/fastapi  
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana-oss:10.4.1
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana   
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitor-net

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitor-net

volumes:
  grafana-storage:   
networks:
  monitor-net:
